---
# This playbook deploys the whole application stack in this site.  

#- name: apply common configuration to all nodes
#  hosts: all
#  remote_user: root

#  roles:
#    - common

- name: deploy gitlab
  hosts: ansible-test02
#  remote_user: vagrant
#  sudo: yes

  vars_files:
    - vars/main.yml
  roles:
    - { role: geerlingguy.gitlab }
